apiVersion: v2
appVersion: v0.7.1
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.x.x
- condition: mysql.enabled
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 9.x.x
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 2.x.x
description: A Helm chart for Kubernetes
maintainers:
- name: clusterpedia-io
  url: https://github.com/clusterpedia-io/clusterpedia-helm
name: clusterpedia
sources:
- https://github.com/clusterpedia-io/clusterpedia-helm
type: application
version: 2.2.0
