apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeeye.kubesphere.io/v1alpha2","kind":"InspectRule","metadata":{"annotations":{},"labels":{"inspection.jibudata.com/rule-category":"Cluster"},"name":"cluster-event-monitoring"},"spec":{"opas":[{"name":"AbnormalEventsRule","rule":"package inspect.kubeeye\nimport rego.v1\n\ndeny contains msg if {\n    input.kind == \"Event\"\n    input.apiVersion == \"v1\"\n\n    input.metadata.namespace == \"kube-system\"\n\n    level := \"DANGER\"\n    Message := input.reason\n    Reason := input.message\n\n    input.type != \"Normal\"\n\n    msg := {\n        \"Name\": sprintf(\"%v\", [input.metadata.name]),\n        \"Namespace\": sprintf(\"%v\", [input.metadata.namespace]),\n        \"Type\": sprintf(\"%v\", [input.kind]),\n        \"Level\": sprintf(\"%v\", [level]),\n        \"Message\": sprintf(\"%v\", [input.message]),\n        \"Reason\": sprintf(\"%v\", [input.reason])\n    }\n}"}]}}
  creationTimestamp: "2025-06-20T02:50:04Z"
  finalizers:
  - kubeeye.finalizers.kubesphere.io
  generation: 1
  labels:
    inspection.jibudata.com/rule-category: Cluster
  name: cluster-event-monitoring
  resourceVersion: "2917398"
  uid: 2fe9404d-40ba-457c-8db5-5e03ebd72ed4
spec:
  opas:
  - name: AbnormalEventsRule
    rule: |-
      package inspect.kubeeye
      import rego.v1

      deny contains msg if {
          input.kind == "Event"
          input.apiVersion == "v1"

          input.metadata.namespace == "kube-system"

          level := "DANGER"
          Message := input.reason
          Reason := input.message

          input.type != "Normal"

          msg := {
              "Name": sprintf("%v", [input.metadata.name]),
              "Namespace": sprintf("%v", [input.metadata.namespace]),
              "Type": sprintf("%v", [input.kind]),
              "Level": sprintf("%v", [level]),
              "Message": sprintf("%v", [input.message]),
              "Reason": sprintf("%v", [input.reason])
          }
      }
status:
  endImportTime: "2025-06-20T05:22:25Z"
  levelCount:
    warning: 1
  startImportTime: "2025-06-20T05:22:24Z"
  state: ImportComplete
