apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeeye.kubesphere.io/v1alpha2","kind":"InspectRule","metadata":{"annotations":{},"labels":{"inspection.jibudata.com/rule-category":"Network"},"name":"kube-apiserver-monitoring"},"spec":{"promQL":[{"desc":"API 服务器非 WATCH 请求速率超过 1000 req/s","name":"KubeAPIServerHighRequestRate","rule":"sum(rate(apiserver_request_total{verb!=\"WATCH\"}[5m])) \u003e 1000"},{"desc":"API 服务器 5xx 错误率超过5%","name":"KubeAPIServerHighErrorRate","rule":"(sum(rate(apiserver_request_total{code=~\"5..\"}[5m])) / sum(rate(apiserver_request_total[5m]))) \u003e 0.05"},{"desc":"API 服务器 4xx 客户端错误率超过10%","name":"KubeAPIServerHighClientErrorRate","rule":"(sum(rate(apiserver_request_total{code=~\"4..\"}[5m])) / sum(rate(apiserver_request_total[5m]))) \u003e 0.1"},{"desc":"API 服务器 GET 请求延迟过高（99分位数超过1秒）","name":"KubeAPIServerHighGetLatency","rule":"histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb=\"GET\"}[5m])) by (resource, le)) \u003e 1"},{"desc":"API 服务器 LIST 请求延迟过高（99分位数超过5秒）","name":"KubeAPIServerHighListLatency","rule":"histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb=\"LIST\"}[5m])) by (resource, le)) \u003e 5"},{"desc":"API 服务器变更请求延迟过高（99分位数超过2秒）","name":"KubeAPIServerHighMutatingLatency","rule":"histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb=~\"CREATE|UPDATE|PATCH|DELETE\"}[5m])) by (verb, resource, le)) \u003e 2"},{"desc":"API 服务器 Pod 资源请求率过高（超过500 req/s）","name":"KubeAPIServerHighPodRequestRate","rule":"sum(rate(apiserver_request_total{resource=\"pods\", verb!=\"WATCH\"}[5m])) \u003e 500"},{"desc":"Pod 创建操作延迟过高（95分位数超过3秒）","name":"KubeAPIServerSlowPodCreation","rule":"histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{resource=\"pods\", verb=\"CREATE\"}[5m])) by (le)) \u003e 3"},{"desc":"API 服务器禁止访问请求过多（超过20 req/s）","name":"KubeAPIServerForbiddenRequests","rule":"sum(rate(apiserver_request_total{code=\"403\"}[5m])) \u003e 20"},{"desc":"API 服务器访问 etcd 延迟过高（99分位数超过500ms）","name":"KubeAPIServerEtcdRequestLatency","rule":"histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (operation, le)) \u003e 0.5"},{"desc":"API 服务器工作队列深度过高（超过100）","name":"KubeAPIServerWorkQueueDepth","rule":"workqueue_depth{name=~\".*apiserver.*\"} \u003e 100"},{"desc":"API 服务器工作队列等待时间过长（99分位数超过1秒）","name":"KubeAPIServerWorkQueueLatency","rule":"histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{name=~\".*apiserver.*\"}[5m])) by (name, le)) \u003e 1"},{"desc":"API 服务器准入控制 Webhook 延迟过高（99分位数超过5秒）","name":"KubeAPIServerAdmissionWebhookLatency","rule":"histogram_quantile(0.99, sum(rate(apiserver_admission_webhook_admission_duration_seconds_bucket[5m])) by (name, type, le)) \u003e 5"}],"prometheus":{"endpoint":"http://prometheus-k8s.kubesphere-monitoring-system.svc.cluster.local:9090"}}}
  creationTimestamp: "2025-06-20T02:50:10Z"
  finalizers:
  - kubeeye.finalizers.kubesphere.io
  generation: 1
  labels:
    inspection.jibudata.com/rule-category: Network
  name: kube-apiserver-monitoring
  resourceVersion: "2917382"
  uid: aa9acf23-e822-45ae-a052-ad06c1b1bfa3
spec:
  promQL:
  - desc: API 服务器非 WATCH 请求速率超过 1000 req/s
    name: KubeAPIServerHighRequestRate
    rule: sum(rate(apiserver_request_total{verb!="WATCH"}[5m])) > 1000
  - desc: API 服务器 5xx 错误率超过5%
    name: KubeAPIServerHighErrorRate
    rule: (sum(rate(apiserver_request_total{code=~"5.."}[5m])) / sum(rate(apiserver_request_total[5m])))
      > 0.05
  - desc: API 服务器 4xx 客户端错误率超过10%
    name: KubeAPIServerHighClientErrorRate
    rule: (sum(rate(apiserver_request_total{code=~"4.."}[5m])) / sum(rate(apiserver_request_total[5m])))
      > 0.1
  - desc: API 服务器 GET 请求延迟过高（99分位数超过1秒）
    name: KubeAPIServerHighGetLatency
    rule: histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb="GET"}[5m]))
      by (resource, le)) > 1
  - desc: API 服务器 LIST 请求延迟过高（99分位数超过5秒）
    name: KubeAPIServerHighListLatency
    rule: histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb="LIST"}[5m]))
      by (resource, le)) > 5
  - desc: API 服务器变更请求延迟过高（99分位数超过2秒）
    name: KubeAPIServerHighMutatingLatency
    rule: histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{verb=~"CREATE|UPDATE|PATCH|DELETE"}[5m]))
      by (verb, resource, le)) > 2
  - desc: API 服务器 Pod 资源请求率过高（超过500 req/s）
    name: KubeAPIServerHighPodRequestRate
    rule: sum(rate(apiserver_request_total{resource="pods", verb!="WATCH"}[5m])) >
      500
  - desc: Pod 创建操作延迟过高（95分位数超过3秒）
    name: KubeAPIServerSlowPodCreation
    rule: histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{resource="pods",
      verb="CREATE"}[5m])) by (le)) > 3
  - desc: API 服务器禁止访问请求过多（超过20 req/s）
    name: KubeAPIServerForbiddenRequests
    rule: sum(rate(apiserver_request_total{code="403"}[5m])) > 20
  - desc: API 服务器访问 etcd 延迟过高（99分位数超过500ms）
    name: KubeAPIServerEtcdRequestLatency
    rule: histogram_quantile(0.99, sum(rate(etcd_request_duration_seconds_bucket[5m]))
      by (operation, le)) > 0.5
  - desc: API 服务器工作队列深度过高（超过100）
    name: KubeAPIServerWorkQueueDepth
    rule: workqueue_depth{name=~".*apiserver.*"} > 100
  - desc: API 服务器工作队列等待时间过长（99分位数超过1秒）
    name: KubeAPIServerWorkQueueLatency
    rule: histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{name=~".*apiserver.*"}[5m]))
      by (name, le)) > 1
  - desc: API 服务器准入控制 Webhook 延迟过高（99分位数超过5秒）
    name: KubeAPIServerAdmissionWebhookLatency
    rule: histogram_quantile(0.99, sum(rate(apiserver_admission_webhook_admission_duration_seconds_bucket[5m]))
      by (name, type, le)) > 5
  prometheus:
    endpoint: http://prometheus-k8s.kubesphere-monitoring-system.svc.cluster.local:9090
status:
  endImportTime: "2025-06-20T05:22:25Z"
  levelCount:
    warning: 13
  startImportTime: "2025-06-20T05:22:24Z"
  state: ImportComplete
