apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeeye.kubesphere.io/v1alpha2","kind":"InspectRule","metadata":{"annotations":{},"labels":{"inspection.jibudata.com/rule-category":"Node"},"name":"node-stats-check"},"spec":{"opas":[{"name":"CheckEphemeralStorageUsage","rule":"package inspect.kubeeye.nodeStatsSummary\nimport rego.v1\n\n# 定义阈值 (5GB in bytes)\nthreshold := 5 * 1024 * 1024 * 1024\n\ndeny contains msg if {\n\n  pod := input.pods[_]\n  storage := pod[\"ephemeral-storage\"]\n  bytes := storage.usedBytes\n  bytes \u003e threshold\n  \n  gb_used := bytes / (1024 * 1024 * 1024)\n\n  level := \"danger\"\n  msg := {\n    \"Name\": sprintf(\"%v\", [pod.podRef.name]),\n    \"Namespace\": sprintf(\"%v\", [pod.podRef.namespace]),\n    \"Type\": \"Pod\",\n    \"Level\": sprintf(\"%v\", [level]),\n    \"Message\": sprintf(\"Pod '%v/%v' 临时存储使用量 (%.2f GB) 超过阈值 (5 GB)\", [pod.podRef.namespace, pod.podRef.name, gb_used]),\n    \"Reason\": \"Pod 临时存储使用量超过阈值\"\n  }\n}"}]}}
  creationTimestamp: "2025-06-20T02:50:15Z"
  finalizers:
  - kubeeye.finalizers.kubesphere.io
  generation: 1
  labels:
    inspection.jibudata.com/rule-category: Node
  name: node-stats-check
  resourceVersion: "2917391"
  uid: 97a4832b-2640-44e9-a8a0-0c30b57ca963
spec:
  opas:
  - name: CheckEphemeralStorageUsage
    rule: "package inspect.kubeeye.nodeStatsSummary\nimport rego.v1\n\n# 定义阈值 (5GB
      in bytes)\nthreshold := 5 * 1024 * 1024 * 1024\n\ndeny contains msg if {\n\n
      \ pod := input.pods[_]\n  storage := pod[\"ephemeral-storage\"]\n  bytes :=
      storage.usedBytes\n  bytes > threshold\n  \n  gb_used := bytes / (1024 * 1024
      * 1024)\n\n  level := \"danger\"\n  msg := {\n    \"Name\": sprintf(\"%v\",
      [pod.podRef.name]),\n    \"Namespace\": sprintf(\"%v\", [pod.podRef.namespace]),\n
      \   \"Type\": \"Pod\",\n    \"Level\": sprintf(\"%v\", [level]),\n    \"Message\":
      sprintf(\"Pod '%v/%v' 临时存储使用量 (%.2f GB) 超过阈值 (5 GB)\", [pod.podRef.namespace,
      pod.podRef.name, gb_used]),\n    \"Reason\": \"Pod 临时存储使用量超过阈值\"\n  }\n}"
status:
  endImportTime: "2025-06-20T05:22:25Z"
  levelCount:
    warning: 1
  startImportTime: "2025-06-20T05:22:24Z"
  state: ImportComplete
