{{- if not .Values.controllerManager.disabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clusterpedia.controllerManager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
{{- end }}
