{{- if .Values.ingress.enabled -}}
{{- $fullName := include "qiming-operator.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "qiming-operator.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
        - backend:
            service:
              name: ui-service-default
              port: 
                number: 9000
          path: {{ .Values.ingress.path }}
          pathType: {{ .Values.ingress.pathType }}
          property:
            ingress.beta.kubernetes.io/enable-checksession: "true"
      {{ if .Values.console_domain }}
      {{if not (.Values.console_domain | regexMatch "^(((25[0-5]|2[0-4][0-9]|1?[0-9]?[0-9])\\.){3}(25[0-5]|2[0-4][0-9]|1?[0-9]?[0-9])[,$]?)+$") }}
      host: {{ .Values.console_domain }}
      {{ end }}
      {{ end }}
    {{- if eq .Values.setCustomDomain "true" }}
    - http:
        paths:
          - backend:
              service:
                name: ui-service-default
                port:
                  number: 9000
            path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            property:
              ingress.beta.kubernetes.io/enable-checksession: "true"
      host: {{ .Values.customDomain }}
    {{- end }}
{{- end }}
