{{- if .Values.createOrUpdateMigConfig }}
apiVersion: migration.yinhestor.com/v1alpha1
kind: Migconfig
metadata:
  name: qiming-config
  labels:
    app.kubernetes.io/name: qiming-operator
    app.kubernetes.io/instance: qiming-config.{{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  version: {{ .Chart.AppVersion }}
  clientName: {{ .Values.migconfig.clientName }}
  serviceAccountName: {{ include "qiming-operator.serviceAccountName" . }}
  deploymentMode: {{ .Values.migconfig.deploymentMode }}
  isAdminCluster: {{ .Values.migconfig.isAdminCluster }}
  agentNamespace: {{ .Values.migconfig.agentNamespace }}
  featureGates:
    {{- range $key, $val := .Values.featureGates }}
    {{ $key }}: {{ $val }}
    {{- end }}
  image:
    registry: {{ .Values.global.imageRegistry | default .Values.imageBase.registry }}
    pullPolicy: {{ .Values.imageBase.pullPolicy }}
    tag: {{ .Values.imageBase.tag }}
  auth:
    issuer: {{ .Values.dex.config.issuer }}
    {{- with (first .Values.dex.config.staticClients) }}
    redirectURI: {{ (first .redirectURIs) }}
    {{- end }}
    {{- with .Values.migconfig.auth.connectors }}
    connectors:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  tenant:
    namespacePrefix: "workspace-"
  {{- with .Values.migconfig.template }}
  template: {{- toYaml . | nindent 4 }}
  {{- end }}
  deletionPolicy: {{- toYaml .Values.migconfig.deletionPolicy | nindent 4 }}
  watchedNamespaces:
  - "*"
  {{- toYaml .Values.components | nindent 2 }}
{{- end }}
