{{- if and .Release.IsUpgrade (not .Values.createOrUpdateMigConfig) }}
apiVersion: migration.yinhestor.com/v1alpha1
kind: Migconfig
metadata:
  name: qiming-config
  labels:
    app.kubernetes.io/name: qiming-operator
    app.kubernetes.io/instance: qiming-config.{{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  version: {{ .Chart.AppVersion }}
  image:
    tag: {{ .Values.imageBase.tag }}
{{- end }}
