{{- if .Values.selfBackup.enabled }}
apiVersion: ys.jibudata.com/v1beta1
kind: BackupPolicy
metadata:
  name: ys1000-self-backup-internal
  labels:
    {{- include "qiming-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: self-backup
spec:
  displayName: 'self backup policy'
  frequency: {{ .Values.selfBackup.frequency }}
  retention: {{ .Values.selfBackup.retention }}
  profile:
    copyMethod: filesystem
{{- end }}
