apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectRule
metadata:
  labels:
    inspection.jibudata.com/rule-category: Storage
  name: filechange-inspect-rules
  resourceVersion: "57353382"
  uid: b38d0aec-500f-4db3-909d-0b3a525de4c3
spec:
  fileChange:
  - name: kubelet-config
    path: /var/lib/kubelet/config.yaml

