apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectRule
metadata:
  labels:
    inspection.jibudata.com/rule-category: Storage
  name: filter-file-inspect-rules
spec:
  fileFilter:
  - name: systemLog
    path: /var/log/syslog
    rule: error

