apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectRule
metadata:
  labels:
    inspection.jibudata.com/rule-category: Node
  name: node-stats-summary-inspect-rules
spec:
  opas:
  - name: CheckDuplicateSubnets
    rule: "package inspect.kubeeye.nodeStatsSummary\nimport rego.v1\n\n# 定义阈值 (5GB
      in bytes)\nthreshold := 5 * 1024 * 1024 * 1024\n\ndeny contains msg if {\n\n
      \ pod := input.pods[_]\n  storage := pod[\"ephemeral-storage\"]\n  bytes :=
      storage.usedBytes\n  bytes > threshold\n  \n  gb_used := bytes / (1024 * 1024
      * 1024)\n\n  level := \"danger\"\n  msg := {\n    \"Name\": sprintf(\"%v\",
      [pod.podRef.name]),\n    \"Namespace\": sprintf(\"%v\", [pod.podRef.namespace]),\n
      \   \"Type\": \"Pod\",\n    \"Level\": sprintf(\"%v\", [level]),\n    \"Message\":
      sprintf(\"Pod '%v/%v' ephemeral-storage usage (%.2f GB) exceeds threshold (5
      GB)\", [pod.podRef.namespace, pod.podRef.name, gb_used]),\n    \"Reason\": \"Pod
      ephemeral-storage usage exceeds threshold\"\n  }\n}"

