apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qiming-operator.fullname" . }}
  labels:
    {{- include "qiming-operator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: qiming-operator
      {{- include "qiming-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: qiming-operator
        {{- include "qiming-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IMAGE_UI
          value: "{{ .Values.components.portal.image.registry | default .Values.imageBase.registry }}/{{ .Values.components.portal.image.repository }}:{{ .Values.components.portal.image.tag | default .Values.imageBase.tag }}"
        - name: IMAGE_DISCOVERY
          value: "{{ .Values.components.discovery.image.registry | default .Values.imageBase.registry }}/{{ .Values.components.discovery.image.repository }}:{{ .Values.components.discovery.image.tag | default .Values.imageBase.tag }}"
        - name: IMAGE_MIG_CONTROLLER
          value: "{{ .Values.components.controller.image.registry | default .Values.imageBase.registry }}/{{ .Values.components.controller.image.repository }}:{{ .Values.components.controller.image.tag | default .Values.imageBase.tag }}"
        - name: IMAGE_CRON
          value: "{{ .Values.components.cron.image.registry | default .Values.imageBase.registry }}/{{ .Values.components.cron.image.repository }}:{{ .Values.components.cron.image.tag | default .Values.imageBase.tag }}"
        - name: HOOK_RUNNER_IMAGE
          value: "{{ .Values.componentImages.hookRunner.registry | default .Values.imageBase.registry }}/{{ .Values.componentImages.hookRunner.repository }}:{{ .Values.componentImages.hookRunner.tag | default .Values.imageBase.tag }}"
        - name: UI_ENABLE_FLAG
          value: "true"
        - name: VELERO_DISABLE_SNAPSHOT
          value: {{ .Values.components.velero.snapshotDisabled | quote }}
        - name: POD_VOLUME_OPERATION_TIMEOUT
          value: {{ .Values.velero.resticPodVolumeOperationTimeout }}
        image: "{{ .Values.image.registry | default .Values.imageBase.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.imageBase.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.imageBase.pullPolicy }}
        name: manager 
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "qiming-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      
