apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gocas.fullname" . }}
  labels:
    {{- include "gocas.labels" . | nindent 4 }}
data:
  gocas.yaml: |-
    {{- include "common.tplvalues.render" ( dict "value" .Values.config "context" $ ) | nindent 4 }}
