apiVersion: v1
kind: Service
metadata:
  name: {{ include "gocas.fullname" . }}
  labels:
    {{- include "gocas.labels" . | nindent 4 }}
spec:
  ports:
  - nodePort: 31888
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cas
    {{- include "gocas.selectorLabels" . | nindent 4 }}
  type: NodePort
