kind: ClusterRole
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'

---
kind: Role
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'