apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: mysql
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: mysql
        {{- if .Values.primary.args }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.primary.args "context" $) | nindent 10 }}
        {{- end }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mysql.fullname" . }}
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: {{ .Values.auth.database | quote }}
        ports:
        - containerPort: 3306
          name: mysql
        {{- if .Values.primary.resources }}
        resources: {{ toYaml .Values.primary.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        {{- if .Values.primary.configuration }}
        - name: config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        {{- end }}
      {{- if .Values.metrics.enabled }}
      - name: metrics
        image: "{{ .Values.metrics.image.registry }}/{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "mysql.fullname" . }}
                key: mysql-root-password
        command:
          - /bin/bash
          - -ec
          - |
            password_aux="${MYSQL_ROOT_PASSWORD:-}"
            DATA_SOURCE_NAME="root:${password_aux}@(localhost:3306)/" /bin/mysqld_exporter {{- range .Values.metrics.extraArgs.primary }} {{ . }} {{- end }}
        ports:
          - name: metrics
            containerPort: 9104
        {{- if .Values.metrics.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.metrics.livenessProbe "enabled" | toYaml | nindent 10 }}
          httpGet:
            path: /metrics
            port: metrics
        {{- end }}
        {{- if .Values.metrics.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.metrics.readinessProbe "enabled" | toYaml | nindent 10 }}
          httpGet:
            path: /metrics
            port: metrics
        {{- end }}
        {{- if .Values.metrics.resources }}
        resources: {{- toYaml .Values.metrics.resources | nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
      {{- if .Values.primary.configuration }}
      - name: config
        configMap:
          name: {{ include "mysql.fullname" . }}
      {{- end }}
      {{- if .Values.primary.persistence.enabled }}
      {{- if .Values.primary.persistence.nfsEnabled }}
      - name: data
        nfs:
          server: {{ .Values.primary.persistence.nfs.server }}
          path: {{ .Values.primary.persistence.nfs.path }}
      {{- else }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "mysql.fullname" . }}
      {{- end }}
      {{- else }}
      - name: data
        emptyDir: {}
      {{- end }}
