apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  clusterIP: None
